// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqiby_GLjsP_N_6H5nkLbdndGxGdkPkyk',
    appId: '1:1037897581705:web:7afbb7752a73675e07f258',
    messagingSenderId: '1037897581705',
    projectId: 'dopai-2c66f',
    authDomain: 'dopai-2c66f.firebaseapp.com',
    storageBucket: 'dopai-2c66f.appspot.com',
    measurementId: 'G-C8QYVTKH3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIb4ONLQkHLJyyc8aA0yVMaf5gS8spalg',
    appId: '1:1037897581705:android:dbed89a57b0fc84f07f258',
    messagingSenderId: '1037897581705',
    projectId: 'dopai-2c66f',
    storageBucket: 'dopai-2c66f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB81Iao4zIElavehpYib8tHF1bNX7B8OaE',
    appId: '1:1037897581705:ios:94027d93a17bf7d307f258',
    messagingSenderId: '1037897581705',
    projectId: 'dopai-2c66f',
    storageBucket: 'dopai-2c66f.appspot.com',
    iosClientId: '1037897581705-chdu7km9vq2m1kgiuumkne5bqasd7ivo.apps.googleusercontent.com',
    iosBundleId: 'com.example.dopproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB81Iao4zIElavehpYib8tHF1bNX7B8OaE',
    appId: '1:1037897581705:ios:94027d93a17bf7d307f258',
    messagingSenderId: '1037897581705',
    projectId: 'dopai-2c66f',
    storageBucket: 'dopai-2c66f.appspot.com',
    iosClientId: '1037897581705-chdu7km9vq2m1kgiuumkne5bqasd7ivo.apps.googleusercontent.com',
    iosBundleId: 'com.example.dopproject',
  );
}
